### ISSUE TITLE
Problems with example - missing file tabulator_midnight.min.css

### ISSUE THREAD

**Issue by colinl** [omrid01/node-red-dashboard-2-table-tabulator#3]
Having imported the example, when I deploy I see
```
ui-tabulator: creating ui-tabulator server node ebf128a3b696ce43
Cannot read CSS file:  Error: ENOENT: no such file or directory, open '/home/me/.node-red/node_modules/@omrid01/node-red-dashboard-2-table-tabulator/nodes/../node_modules/tabulator-tables/dist/css/tabulator_midnight.min.css'
    at readFileSyncUtf8 (node:internal/fs/read/utf8:20:3)
    at Object.readFileSync (node:fs:467:12)
    at new UITabulatorNode (/home/colinl/.node-red/node_modules/@omrid01/node-red-dashboard-2-table-tabulator/nodes/ui-tabulator.js:198:20)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:190:27)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:261:54)
    at async start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:403:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/me/.node-red/node_modules/@omrid01/node-red-dashboard-2-table-tabulator/nodes/../node_modules/tabulator-tables/dist/css/tabulator_midnight.min.css'
}
```

In addition there are  a couple of minor issues, it is throwing linter errors as you have two unnamed functions and Function 84 has irregular indenting.

**Comment by omrid01** [comment]
Thanks Colin.
Turns out that the standard NPM installation puts the tabulator package in a different location than in my development environment, so it screwed up the path to the CSS file.
Will fix and release a new version.
Can you point me to the linter errors in the code?

**Comment by colinl** [comment]
> Can you point me to the linter errors in the code?

Function 84 has an extra space in line 5 and the two functions in the Table Appearance group have not got names.

**Comment by omrid01** [comment]
OK, got it, it's in the example flow. Will fix.
Thanks.
